build:
    script:
        - ./sdrtool build Debug
    only:
        - development

unittest:
    script:
        - ./sdrtool build Unittest
        - rm -vr data
        - ln -s ~/sdrdab-test/data data
        - ./sdrtool run-unittests
    only:
        - development
